services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - grafana
    volumes:
      - app-data:/app

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-data:/prometheus
      - /root/Analise-Preditiva-de-Tendencias-do-Bitcoin-com-Mineracao-de-Dados/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  monitoring:
    driver: bridge

volumes:
  app-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
